//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportManagemantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doing
    {
        public long doingID { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<long> dutyID { get; set; }
        public Nullable<int> timeDistanse { get; set; }
    
        public virtual Duty Duty { get; set; }
        public virtual User User { get; set; }
    }
}
