//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportManagemantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Duty()
        {
            this.Doings = new HashSet<Doing>();
        }
    
        public long dutyID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> requiredTime { get; set; }
        public Nullable<byte> piorityID { get; set; }
        public Nullable<bool> done { get; set; }
        public Nullable<long> requestID { get; set; }
        public Nullable<int> registerID { get; set; }
        public Nullable<int> referedToUserID { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> companyID { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doing> Doings { get; set; }
        public virtual Piority Piority { get; set; }
        public virtual Project Project { get; set; }
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
