//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportManagemantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Query()
        {
            this.Executes = new HashSet<Execute>();
        }
    
        public long queryID { get; set; }
        public string queryCommand { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> companyID { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Execute> Executes { get; set; }
        public virtual Project Project { get; set; }
        public virtual QueryType QueryType { get; set; }
        public virtual User User { get; set; }
    }
}
