//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportManagemantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Response()
        {
            this.TicketFiles = new HashSet<TicketFile>();
        }
    
        public long responseID { get; set; }
        public Nullable<long> ticketID { get; set; }
        public string answer { get; set; }
        public Nullable<int> answererID { get; set; }
        public string estimatedDate { get; set; }
        public Nullable<long> requestID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketFile> TicketFiles { get; set; }
    }
}
