//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportManagemantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long taskID { get; set; }
        public string decription { get; set; }
        public string date { get; set; }
        public Nullable<double> spentTime { get; set; }
        public Nullable<long> ticketID { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Project Project { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
